version: '3.8'

services:
  db:
    image: "postgres"
    container_name: "kiii-project-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kiii
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  spring-boot-app:
    build: .
    container_name: "kii-project-spring-boot"
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/kiii
      db-username: postgres
      db-password: postgres
    depends_on:
      - db
    restart: always

volumes:
  postgres-data: