apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-configmap
  namespace: kiii
data:
  POSTGRES_DB: "kiii"
  POSTGRES_USER: "postgres"

---

apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
  namespace: kiii
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  namespace: kiii
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sts
  namespace: kiii
spec:
  serviceName: db-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: kiii
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pg-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: kiii
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      